package com.avitech.sia.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class LoteDAO {

    public record Lote(int id, String nombreLote, String estado, int cantidadGallinas) {
        // Constructor for new Lotes (ID will be generated by DB)
        public Lote(String nombreLote, String estado, int cantidadGallinas) {
            this(0, nombreLote, estado, cantidadGallinas);
        }

        // Getters for JavaFX properties (if needed, or use direct access)
        public int getId() { return id; }
        public String getNombreLote() { return nombreLote; }
        public String getEstado() { return estado; }
        public int getCantidadGallinas() { return cantidadGallinas; }

        // Setters for updating existing Lote objects (if needed)
        public Lote setNombreLote(String nombreLote) { return new Lote(this.id, nombreLote, this.estado, this.cantidadGallinas); }
        public Lote setEstado(String estado) { return new Lote(this.id, this.nombreLote, estado, this.cantidadGallinas); }
        public Lote setCantidadGallinas(int cantidadGallinas) { return new Lote(this.id, this.nombreLote, this.estado, cantidadGallinas); }
    }

    public int getTotalActiveGallinas() throws Exception {
        String sql = "SELECT SUM(cantidadGallinas) FROM Lote WHERE estado = 'Activo'";
        try (Connection conn = DB.get();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            return rs.next() ? rs.getInt(1) : 0;
        }
    }

    public List<Lote> getAllLotes() throws Exception {
        List<Lote> lotes = new ArrayList<>();
        String sql = "SELECT Id_lote, nombre_lote, estado, cantidadGallinas FROM Lote ORDER BY nombre_lote";

        try (Connection conn = DB.get();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                lotes.add(new Lote(
                        rs.getInt("Id_lote"),
                        rs.getString("nombre_lote"),
                        rs.getString("estado"),
                        rs.getInt("cantidadGallinas")
                ));
            }
        }
        return lotes;
    }

    public void insert(Lote lote) throws Exception {
        String sql = "INSERT INTO Lote (nombre_lote, estado, cantidadGallinas) VALUES (?, ?, ?)";
        try (Connection conn = DB.get();
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, lote.nombreLote());
            ps.setString(2, lote.estado());
            ps.setInt(3, lote.cantidadGallinas());
            ps.executeUpdate();

            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    // Lote record is immutable, so we can't set the ID directly.
                    // In a real app, you might return the new Lote with ID or refetch.
                }
            }
        }
    }

    public void update(Lote lote) throws Exception {
        String sql = "UPDATE Lote SET nombre_lote=?, estado=?, cantidadGallinas=? WHERE Id_lote=?";
        try (Connection conn = DB.get();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, lote.nombreLote());
            ps.setString(2, lote.estado());
            ps.setInt(3, lote.cantidadGallinas());
            ps.setInt(4, lote.id());
            ps.executeUpdate();
        }
    }

    public void delete(int id) throws Exception {
        String sql = "DELETE FROM Lote WHERE Id_lote=?";
        try (Connection conn = DB.get();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }
}
